"""Add password and role to users, add 
  contents table

Revision ID: 2e9dea0ca1b7
Revises: 001
Create Date: 2025-08-25 05:19:44.309141+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e9dea0ca1b7'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###
    
    # Insert initial admin user if not exists
    # Password hash for "admin123" using bcrypt: $2b$12$K.QpUJL7rU8lG5t1YxP2U.vG3C3g3bWHFqJ0eHJwN8Z0oF8Z0.oG2
    connection = op.get_bind()
    
    # Check if admin user already exists
    result = connection.execute(
        sa.text("SELECT COUNT(*) as count FROM users WHERE username = 'admin'")
    ).fetchone()
    
    if result[0] == 0:
        connection.execute(
            sa.text("""
                INSERT INTO users (username, email, password_hash, role)
                VALUES ('admin', 'admin@example.com', '$2b$12$K.QpUJL7rU8lG5t1YxP2U.vG3C3g3bWHFqJ0eHJwN8Z0oF8Z0.oG2', 'ADMIN')
            """)
        )
    else:
        # Update existing admin user with password and role
        connection.execute(
            sa.text("""
                UPDATE users 
                SET password_hash = '$2b$12$K.QpUJL7rU8lG5t1YxP2U.vG3C3g3bWHFqJ0eHJwN8Z0oF8Z0.oG2', 
                    role = 'ADMIN'
                WHERE username = 'admin'
            """)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###